apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: python-template
  title: Python flask template
  description: Provisions a minimalistic flask application
  tags:
    - Python
    - Flask
    - Github-Actions
    - Kubernetes
    - ArgoCD
    - Sonarqube
spec:
  owner: platform-engineering
  type: service
  parameters:
    - title: Fill in some steps
      required:
        - app_name
        - squad_name
      properties:
        app_name:
          title: Component name test 
          type: string
          description: Provide a component (microservice) name
          pattern: '^([a-zA-Z][a-zA-Z0-9]*)(-[a-zA-Z0-9]+)*$'
        environment:
          title: Squad
          type: string
          description: Squad Name
          enum:
            - squad-a
            - squad-b
            - squad-c
  steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ./template
        values:
          app_name: ${{parameters.app_name}}
          app_env: ${{parameters.environment}}

    - id: publish
      name: Publish
      action: publish:github
      input:
        # allowedHosts:
        #   - github.com
        description: This is ${{ parameters.app_name }}
        repoUrl: github.com?owner=devops-brotherslab&repo=${{parameters.app_name}}
        defaultBranch: main
        protectDefaultBranch: false
        repoVisibility: public

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: "/catalog-info.yaml"
        


  output:
    links:
      - title: Repository
        url: ${{ steps['publish'].output.remoteUrl }}
